# -*- coding: utf-8 -*-
"""pandas02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AimqhxQl6vOws0wfGOSMLKenZwRUBMBd
"""

import pandas as pd
import numpy as np
import seaborn as sns
from sklearn import preprocessing

pd.set_option('display.max_columns', 8)             # 화면에 출력된 칼럼수를 6개만 표시해라
#pd.set_option('display,unicode.east_asian', True)   # 한글을 출력할 때 줄과 글의 크기가 맞지 않을 때 맞춰줌

df = sns.load_dataset('titanic')
print(df.head(20))

df.info()

nan_deck = df['deck'].value_counts(dropna = False)
print(nan_deck)

print(df.head().isnull())

print(df.head().notnull())

print(df.isnull().sum())

df.dropna(axis = 'columns', thresh = 500, inplace =True)      # thresh 옵션 : NaN 값이 500개 이상이면 그 칼럼을 지워라
print(df.columns)

df_age = df.dropna(subset = ['age'], how = 'any', axis = 'rows' )    # 나이의 값이 있는 row만 남김,
# 칼럼이 2개일 때, how = all -> 둘다 NaN값일 때 제거, how = any -> 하나라도 NaN값이면 지워라
df_age.info()

mean_age = df['age'].mean()                   # pandas는 NaN 값을 빼고 평균을 계산
df['age'].fillna(mean_age, inplace = True)    # 나이는 이상치가 높지 않아서 평균값을 채워 넣어도 된다.
print(df.head(10))

most_freq = df['embark_town'].value_counts(dropna = True).idxmax()
print(most_freq)

df_most_freq = df['embark_town'].fillna(most_freq, inplace = False)
print(df_most_freq[825:830])
print(df[825:830])

df['embark_town'].fillna(method = 'ffill', inplace = True)      # method = 'ffill' -> 이전 값, method = 'bfill' -> 이후 값
# 엑셀 파일의 경우 파일의 데이터 병합이 일어났을 때 밑의 값은 NaN 값으로 채우기에 필요함
print(df[825:830])

df.info()

df.drop(['survived', 'embarked'], axis = 'columns', inplace = True)
df.info()

print(df.isnull().sum())

